### PR TITLE
Improve aligning description

### PR DESCRIPTION
**Pull request by xuchunyang**
- [x] Set as default
- [x] Update README
- [x] Highlight matched item

### CODE REVIEW

**Comment by xuchunyang** [comment]
The default value of `helm-github-stars-name-length` is 30, but feel free to change it.

**Comment by xuchunyang** [comment]
Now, matched item in helm buffer will not be highlighted again (reported in #2 and fixed by https://github.com/Sliim/helm-github-stars/commit/24eb288fc219351660d845aaa6e7baa635a49902)

**Comment by xuchunyang** [comment]
Done! The latest implement of aligning description is simpler and bug-free.

@Sliim When you have time, please review this.

**Comment by Sliim** [comment]
:+1:  Awesome!!!
Merged, it works fine! thanks ;)

**Pull request merged**
